# -*- coding: utf-8 -*-
"""Untitled37.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1StMKIRG8f0RzHiiz9cufiT_wuC146odD
"""

print("EMPLOYEE SALARY SHEET ")

name = input("Enter Employee Name: ")
basic = float(input("Enter Basic Salary: "))

da = (basic*85/100)
ta = (basic*15/100)
hra = (basic*15/100)

gross = basic + da + ta + hra

pf = (gross*8.33/100)

net = gross - pf

print("--- SALARY SHEET ---")
print("Employee Name :", name)
print("Basic Salary :", basic)
print("DA :", da)
print("TA :", ta)
print("HRA :", hra)
print("Gross Salary :", gross)
print("PF :", pf)
print("Net Salary :", net)

